config/routes.rb
Rails.application.routes.draw do
  resources :activities

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_users_session
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :moments

  resources :maps do 
    get '/geojson' => 'maps#geojson'
    post '/send_link_to_friend' => 'maps#send_link_to_friend'
  end

  resources :users do
    post '/follow' => 'users#add_friend_profile'
    get '/friends' => 'users#friends'
    post '/friends' => 'users#add_friend'
    delete '/friends' => 'users#remove_friend'
    get '/geojson' => 'users#geojson'
  end
  
  get '/geojson' => 'welcome#geojson'
  get '/about' => 'welcome#about'

  get '/act/:id' => 'activities#item'
  
  post 'instagram_photo' => 'moments#instagram_photo'

  root 'welcome#index'

end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user
  has_many :moments, -> { order(:created_at) } 
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :geojson]
  
  def new
    @map = Map.new
  end
  
  def create
    map = current_user.new_map(map_params)
    map.save
    track_activity(map)

    redirect_to map_path(map)
  end

  def show
    @map = Map.find(params[:id])
    if @map.publicly_available? || user_signed_in?
      render :show
    else
      redirect_to root_path
    end
  end

  def send_link_to_friend
    @map = current_user.maps.find(params[:map_id])
    SendLink.share_link(@map, params[:friend_email]).deliver_now
    redirect_to map_path(@map)
  end

  def edit
    @map = current_user.maps.find(params[:id])
  end

  def update
    @map = current_user.maps.find(params[:id])
    @map.update(map_params)
    track_activity(@map)

    respond_to do |format|
      format.html { redirect_to map_path(@map) }
      format.js { }
    end
  end
  
  def destroy
    current_user.delete_map(params[:id])

    redirect_to user_path(current_user)
  end
  
  def geojson
    map = Map.find(params[:map_id])
    if map.publicly_available? || user_signed_in?
      @geojson = map.moments.collect do |moment|
        moment.geojson
      end

      render json: @geojson
    else
      redirect_to root_path
    end
  end 
  
  private
    def map_params
      params.require(:map).permit(:name, :publicly_available)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for(map) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> 
  <%= f.submit "Update Map", class: "btn btn-info"  %>
<% end %>

app/views/maps/_map.html.erb
<div class="col-md-8" style="padding:0">
  <div id="map-wrapper">
    <div class="custom-popup" id='map'>
      <script>
        $(function() {
          map = new MakeMap("<%= url %>","<%= action %>");
        });
      </script>
    </div>
  </div>
</div>

app/views/maps/_moment_cards.html.erb
<div class="momentlist col-md-4" style="padding-left:5px;padding-right:5px">

<% if current_user == map.user %>
  <div class="widget">
    <div class="widget-head br-lblue" data-toggle="collapse" data-target="#collapseExample">
      <h3 class= "pull-left"><i class= "fa fa-plus"></i> Add a New Moment</h3>
      <div class="clearfix"></div>
    </div>
    <div class="widget-body collapse" id="collapseExample">
      <%= form_for(map.moments.build, remote: true, :html => {:class => "ui-element-container form-inline", :multipart => true}) do |f| %>
        <div class="form-group input-group input-group-sm">
          <%= f.text_area :memo, :class => 'form-control', :placeholder => 'write about your moment' %>
          <%= f.file_field :image, :class => 'form-control' %>
          <%= f.hidden_field :latitude %>
          <%= f.hidden_field :longitude %>
          <%= f.hidden_field :map_id, value: map.id %>
          <%= f.button "New Moment", :class => "btn btn-info btn-block", :id => "submit" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

  <% map.moments.each do |moment| %>
    <% if moment.persisted? %>
      <div class="widget" id="moment<%= moment.id %>">
        <div class="widget-head br-lblue">
          <% address = Geocoder.address("#{moment.latitude},#{moment.longitude}")%>
          <% if address.is_a? String  %>
            <% address_arr = address.split(',') %>
            <h3 class="pull-left"><i class="fa fa-map-marker"></i> <%= "#{address_arr[1]}, #{address_arr[2].split(" ")[0]} #{address_arr[3]}" %></h3>
          <% else %>
            <h3 class="pull-left"><i class="fa fa-map-marker"></i> <%= moment.latitude %>, <%= moment.longitude %></h3>
          <% end %>
          <% if current_user == map.user %>
          <h3 class="pull-right" style="text-align:center;font-size:10px;"><%= link_to "Edit Moment", edit_moment_path(moment) %> | <%= link_to "Delete Moment", moment_path(moment), {method: :delete, remote: true} %></h3>
          <% end %>
          <div class="clearfix"></div>
        </div>
        <div class="widget-body">
          <%= link_to image_tag(moment.image.url), moment.image.url if moment.image.exists? %>
          <p><%= moment.memo %></p>
           <% if current_user.provider? %>
          <p><%= button_to "Add Most Recent Instagram Photo", instagram_photo_path(id: moment.id) %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/maps/_private_cards.html.erb
<div class="momentlist col-md-4" style="padding-left:5px;padding-right:5px">

  <div class="widget">
    <div class="widget-head br-lblue" data-toggle="collapse" data-target="#collapseExample">
      <h3 class= "pull-left"><i class= "fa fa-plus"></i> Add a New Moment</h3>
      <div class="clearfix"></div>
    </div>
    <div class="widget-body collapse" id="collapseExample">
      <%= form_for(map.moments.build, remote: true, :html => {:class => "ui-element-container form-inline", :multipart => true}) do |f| %>
        <div class="form-group input-group input-group-sm">
          <%= f.text_area :memo, :class => 'form-control', :placeholder => 'write about your moment' %>
          <%= f.file_field :image, :class => 'form-control' %>
          <%= f.hidden_field :latitude %>
          <%= f.hidden_field :longitude %>
          <%= f.hidden_field :map_id, value: map.id %>
          <%= f.button "New Moment", :class => "btn btn-info btn-block", :id => "submit" %>
        </div>
      <% end %>
    </div>
  </div>

  <% map.moments.each do |moment| %>
    <% if moment.persisted? %>
      <div class="widget" id="moment<%= moment.id %>">
        <div class="widget-head br-lblue">
          <% address = Geocoder.address("#{moment.latitude},#{moment.longitude}")%>
          <% if address.is_a? String  %>
            <% address_arr = address.split(',') %>
            <h3 class="pull-left"><i class="fa fa-map-marker"></i> <%= "#{address_arr[1]}, #{address_arr[2].split(" ")[0]} #{address_arr[3]}" %></h3>
          <% else %>
            <h3 class="pull-left"><i class="fa fa-map-marker"></i> <%= moment.latitude %>, <%= moment.longitude %></h3>
          <% end %>
          <h3 class="pull-right" style="text-align:center;font-size:10px;"><%= link_to "Edit Moment", edit_moment_path(moment) %> | <%= link_to "Delete Moment", moment_path(moment), {method: :delete, remote: true} %></h3>
          <div class="clearfix"></div>
        </div>
        <div class="widget-body">
          <%= link_to image_tag(moment.image.url), moment.image.url if moment.image.exists? %>
          <p><%= moment.memo %></p>
           <% if current_user.provider? %>
          <p><%= button_to "Add Most Recent Instagram Photo", instagram_photo_path(id: moment.id) %></p>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/maps/_private_map.html.erb
<%= render layout: "layouts/mainbar" do %>
  <div class="col-md-4 col-sm-4 col-xs-6">
    <h4 class="private-map-text"><i class="fa fa-map lblue"></i> Your Map: <%= @map.name %></h4>
    <%= link_to "rename", edit_map_path(@map) %> <span class="link-divider">|</span> <%= link_to "delete", map_path(@map), method: :delete %>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
  <div class="col-md-4 col-sm-4 col-xs-6">
    <div class="col-md-3">
      <p class="toggle-map">Public</p>
      <div class="slideThree">
        <%= form_for(@map, remote: true) do |f| %>
          <%= f.check_box :publicly_available, :onclick => "$('#edit_map_#{@map.id}').submit()", id: "slideThree" %>
          <label for="slideThree"></label>
        <% end %> 
      </div>
    </div>
    <div class="col-md-9">
    <p>Share This Map with a Friend</p>
      <%= form_tag(map_send_link_to_friend_path(@map), :html => {:class => "ui-element-container form-inline"}) do %>
        <div class="form-group input-group input-group-sm">
          <%= text_field_tag :friend_email, nil, :class => 'form-control', :placeholder => 'friend@hier-ayer.com' %>
          <span class="input-group-btn"><%= submit_tag "Send Email", :class => "btn btn-info", :id => "sendEmail" %></span>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<%= render partial: "map", locals: {url: map_geojson_path(@map), action: "map#show"} %>
<%= render partial: "private_cards", locals: {map: @map} %>


<script>
  if ($("#slideThree").is(':checked') === false) {
    $("#sendEmail").prop('disabled', true);
  } else {
    $("#sendEmail").prop('disabled', false);
  }
  
  $("#submit").val("Automagical ...").prop('disabled', true);
  getCoordinates(function(latitude,longitude){
    $("#moment_latitude").val(latitude);
    $("#moment_longitude").val(longitude);
    $("#submit").val("Create a New Moment").prop('disabled', false);
  });
  
  $("#slideThree").on('click', function(){
    if ($("#slideThree").is(':checked') === false) {
      $("#sendEmail").prop('disabled', true);
    } else {
      $("#sendEmail").prop('disabled', false);
    }
  });
</script>

app/views/maps/_public_cards.html.erb
<div class="momentlist col-md-4" style="padding-left:5px;padding-right:5px">
  <% map.moments.each do |moment| %>
    <% if moment.persisted? %>
      <div class="widget" id="moment<%= moment.id %>">
        <div class="widget-head br-lblue">
          <% address = Geocoder.address("#{moment.latitude},#{moment.longitude}")%>
          <% if address.is_a? String  %>
            <% address_arr = address.split(',') %>
            <h3 class="pull-left"><i class="fa fa-map-marker"></i> <%= "#{address_arr[1]}, #{address_arr[2].split(" ")[0]} #{address_arr[3]}" %></h3>
          <% else %>
            <h3 class="pull-left"><i class="fa fa-map-marker"></i> <%= moment.latitude %>, <%= moment.longitude %></h3>
          <% end %>
          <div class="clearfix"></div>
        </div>
        <div class="widget-body">
          <%= link_to image_tag(moment.image.url), moment.image.url if moment.image.exists? %>
          <p><%= moment.memo %></p>
        </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/maps/_public_map.html.erb
<%= render layout: "layouts/mainbar" do %>
  <div class="col-md-4 col-sm-4 col-xs-6">
    <h4><i class="fa fa-map lblue"></i><%= link_to @map.user.name.capitalize+"'s", user_path(@map.user) %> map: <%= @map.name %></h4>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
<% end %>

<%= render partial: "map", locals: {url: map_geojson_path(@map), action: "map#show"} %>

<%= render partial: "public_cards", locals: {map: @map} %>

app/views/maps/edit.html.erb
<%= render layout: "layouts/mainbar" do %>
  <div class="col-md-4 col-sm-4 col-xs-6">
    <% if @map.user == current_user %>
      <h4><i class="fa fa-map lblue"></i> Editing: <%= @map.name %></h4>
    <% end %>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
<% end %>

<%= render partial: "form", locals: {map: @map} %>

app/views/maps/index.html.erb
<h1>All My Maps</h1> bv 
<% @maps.each do |map| %>
  <%= map %>
<% end %>

app/views/maps/show.html.erb
<% if @map.user == current_user %>
  <%= render partial: "private_map", locals: {map: @map} %>
<% else %>
  <%= render partial: "public_map", locals: {map: @map} %>
<% end %>
 

app/views/maps/update.js.erb
$('#edit_map_<%= @map.id%>').prop('checked', <%= @map.publicly_available %>); 