config/routes.rb
Rails.application.routes.draw do
  resources :activities

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_users_session
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :moments

  resources :maps do 
    get '/geojson' => 'maps#geojson'
    post '/send_link_to_friend' => 'maps#send_link_to_friend'
  end

  resources :users do
    post '/follow' => 'users#add_friend_profile'
    get '/friends' => 'users#friends'
    post '/friends' => 'users#add_friend'
    delete '/friends' => 'users#remove_friend'
    get '/geojson' => 'users#geojson'
  end
  
  get '/geojson' => 'welcome#geojson'
  get '/about' => 'welcome#about'

  get '/act/:id' => 'activities#item'
  
  post 'instagram_photo' => 'moments#instagram_photo'

  root 'welcome#index'

end

app/views/send_link/share_link.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type'/>
</head>
<body>
  <p><%=@map.user.name.capitalize%> has shared a moment with you!</p>
  <p>Here you go! <%= map_url(@map) %>.</p>
  <p>You can register for your own account with <a href="http://hier-ayer.herokuapp.com/">Ayer</a>.</p>
  <p>Happy viewing.</p>
</body>
</html>

app/views/send_link/share_link.text.erb
<%=@map.user.name%> has shared a moment with you!
======================================================
<%=@map.user.name%> has shared a moment with you!

Here you go! <%= link_to "see my moment", user_path(@map.user) %>.

You can register for your own account with http://hier-ayer.herokuapp.com/

Happy viewing.