config/routes.rb
Rails.application.routes.draw do
  resources :activities

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_users_session
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :moments

  resources :maps do 
    get '/geojson' => 'maps#geojson'
    post '/send_link_to_friend' => 'maps#send_link_to_friend'
  end

  resources :users do
    post '/follow' => 'users#add_friend_profile'
    get '/friends' => 'users#friends'
    post '/friends' => 'users#add_friend'
    delete '/friends' => 'users#remove_friend'
    get '/geojson' => 'users#geojson'
  end
  
  get '/geojson' => 'welcome#geojson'
  get '/about' => 'welcome#about'

  get '/act/:id' => 'activities#item'
  
  post 'instagram_photo' => 'moments#instagram_photo'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, 
  :rememberable, :trackable, :validatable, :omniauthable

  has_many :maps, -> { order(:created_at) } 
  has_many :moments, through: :maps
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :activities

  has_attached_file :avatar, 
                    :styles => { :thumb => "100x100#" },
                    :default_url => "missing_avatar.jpg"
  has_attached_file :image
  validates_attachment_presence :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.nickname
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def new_map(map_params)
    self.maps.build(map_params)
  end

  def delete_map(map_id)
    map = self.maps.find(map_id)
    map.destroy
  end
  
  def user_exists?(user)
    !!User.find_by(name: user)
  end

  def add_friend(friend_name)
    if friend_name == self.name
      "Sorry, narcissist, you can't follow yourself"
    elsif self.friends.include?(User.find_by(name: friend_name))
      "Already following #{friend_name}"
    elsif user_exists?(friend_name)
      self.friends << User.find_by(name: friend_name)
      self.activities.create(action: "follow", trackable: User.find_by(name: friend_name))
      "Now following #{friend_name}!"
    else
      "Sorry, no such user"
    end
  end

  def unfriend(friend_id)
    friendships = self.friendships.find_by(friend_id: friend_id)
    friendships.destroy
    self.reload
  end

  def followers
    self.inverse_friends
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
 
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end 

  def geojson 
    maps = User.find(params[:user_id]).maps
    @geojson = maps.collect do |map|
      map.moments.collect do |moment|
        moment.geojson
      end
    end.flatten

    render json: @geojson
  end

  def add_friend_profile
    @friend = User.find(params[:friend_id])
    message = current_user.add_friend(@friend.name)

    flash.now[:notice] = message

    respond_to do |format|
      format.html { redirect_to user_path(@friend) }
      format.js { }
    end

  end

  def add_friend
    @friend = User.find_by(name: params[:friend_name])
    message = current_user.add_friend(@friend.name)
    flash.now[:notice] = message
    respond_to do |format|
      format.html { redirect_to user_path(@friend) }
      format.js { }
    end
  end

  def remove_friend
    @friend_id = params[:friend_id]
    current_user.unfriend(@friend_id)
    respond_to do |format|
      format.html { redirect_to user_path(current_user) }

      format.js { }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_bigmap.html.erb
<div class="col-md-9">
  <div id="map-wrapper">
    <div class="custom-popup" id= 'map'>
      <script>
        $(function() {
          new MakeMap("<%= user_geojson_path(user) %>","user#show");
        });
      </script>
    </div>
  </div>
</div>

app/views/users/_minimap.html.erb
<div class="sidemaps col-md-3">
  <% user.maps.each do |map| %>
    <a href="/maps/<%= map.id %>"><div class="minimap" id="map-<%= map.id %>">
      <script>
        new MakeMap("<%= map_geojson_path(map) %>","minimap","<%= map.id %>");
      </script>
      <div class="title"><p class="map-overlay-title"><%= map.name %></p></div>
    </div></a>
  <% end %>
</div>

app/views/users/_private_profile.html.erb
<%= render layout: "layouts/mainbar" do %>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
  <div class="col-md-4 col-sm-4 col-xs-6">
    <div class="pull-right">
      <h4 class="user-profile-text">Your Profile <i class="fa fa-user lblue"></i></h4>
      <%= link_to edit_user_registration_path, class: "user-edit-link" do %>
        <i class="fa fa-cog"></i>
      <% end %>
    </div>
  </div>
<% end %>


<%= render partial: "bigmap", locals: {user: current_user} %>
<%= render partial: "minimap", locals: {user: current_user} %>

app/views/users/_public_profile.html.erb
<%= render layout: "layouts/mainbar" do %>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
  <div class="col-md-4 col-sm-4 col-xs-6"></div>
  <div class="col-md-4 col-sm-4 col-xs-6">
    <div class="pull-right">
      <h4><%= link_to "follow ", user_follow_path(current_user, :friend_id => user.id), method: :post, remote: true%><%= @user.name.capitalize %>'s Profile <%=image_tag @user.avatar.url(:thumb), :class => "img-responsive img-circle"%></h4>
    </div>
  </div>
<% end %>

<%= render partial: "bigmap", locals: {user: @user} %>
<%= render partial: "minimap", locals: {user: @user} %>

<div class="col-md-9">
  <div class="col-md-6" style="padding-top:5px">
    <ul class="list-unstyled">
    <h6><%=@user.name.capitalize%>'s Following:</h6>
    <% @user.friends.each do |friend| %>
    <%=image_tag friend.avatar.url(:thumb), :class => "img-responsive img-circle-frfo"%>
    <%= link_to friend.name, user_path(friend) %>
    <% end %>
    </ul>
  </div>

  <div class="col-md-6" style="padding-left:5px;padding-top:5px">
    <ul class="list-unstyled">
      <li>
      <h6><%=@user.name.capitalize%>'s Followers: </h6>
        <% @user.followers.each do |friend| %>
        <%=image_tag friend.avatar.url(:thumb), :class => "img-responsive img-circle-frfo"%>
        <%= link_to friend.name, user_path(friend) %>
      </li>
    <% end %>
    </ul>
  </div>
</div>  

app/views/users/_sidebar.html.erb
<!-- Sidebar starts -->
<div class="sidebar">

  <div class="sidey">

    <!-- Logo -->
    <div class="logo">
      <h1><a href="/"><i class="fa fa-map-pin br-red"></i> Ayer <span>Map Nostalgia</span></a></h1>
    </div>
    
    <!-- Sidebar navigation starts -->
    
    <!-- Responsive dropdown -->
    <div class="sidebar-dropdown"><a href="#" class="br-red"><i class="fa fa-bars"></i></a></div>
    
    <div class="side-nav">
    
      <div class="side-nav-block">
        <!-- Sidebar heading -->
        <h4>Menu</h4>
        <!-- Sidebar links -->
        <ul class="list-unstyled">
          <li><a href="<%= root_path %>"><i class="fa fa-home"></i> Home </a></li>
          <!-- Mainmenu with submenu -->
          <li class="has_submenu">
            <a href="#"><i class="fa fa-user"></i> Profile <span id="submenu" class="nav-caret fa fa-caret-down"></span></a>
            <!-- Submenu -->
            <ul class="list-unstyled">
              <li><i class="fa fa-angle-double-right"></i>  <%= link_to "Your Profile", user_path(current_user) %></li>
              <li><i class="fa fa-angle-double-right"></i>  <%= link_to "Edit Info", edit_user_registration_path %></li>
            </ul>
          </li>
          <!-- Mainmenu with submenu -->
          <li class="has_submenu">
            <a href="#"><i class="fa fa-map-o"></i> Maps <span class="badge badge-danger pull-right"><%= current_user.maps.count %></span><span id="submenu" class="nav-caret fa fa-caret-down"></span></a>
            <!-- Submenu -->
            <ul class="list-unstyled">
              <% current_user.maps.each do |map| %>
                <li class="mapListItem" ><i class="fa fa-angle-double-right"></i>  <%= link_to map.name, map_path(map) %></li>
              <% end %>
            </ul>
          </li>
          <!-- Mainmenu with submenu -->
          <li class="has_submenu">
            <a href="#"><i class="fa fa-heart"></i> Following <span class="badge badge-danger pull-right"><%= current_user.friends.count %></span><span id="submenu" class="nav-caret fa fa-caret-down"></span></a>
            <!-- Submenu -->
            <ul class="list-unstyled">
              <% current_user.friends.each do |friend| %>
                <li><i class="fa fa-angle-double-right"></i>  <%= link_to friend.name, user_path(friend) %></li>
              <% end %>
            </ul>
          </li>
          <!-- Mainmenu with submenu -->
          <li class="has_submenu">
            <a href="#"><i class="fa fa-users"></i> Followers <span class="badge badge-danger pull-right"><%= current_user.followers.count %></span><span id="submenu" class="nav-caret fa fa-caret-down"></span></a>
            <!-- Submenu -->
            <ul class="list-unstyled">
              <% current_user.followers.each do |follower| %>
                <li><i class="fa fa-angle-double-right"></i>  <%= link_to follower.name, user_path(follower) %></li>
              <% end %>
            </ul>
          </li>
          <li><%= link_to destroy_user_session_path, :method => :delete do %>
            <i class="fa fa-sign-out"></i>
            Sign Out
          <% end %></li>         
        </ul>
      </div>
    </div>
    <!-- Sidebar navigation ends -->
  </div>
</div>
<!-- Sidebar ends -->

app/views/users/add_friend.js.erb
var html = '<li id= \'<%=@friend.id%>\'><%= image_tag @friend.avatar.url(:thumb), :class => "img-responsive img-circle-frfo"%> <%= link_to @friend.name, user_path(@friend)%> <span class= "pull-right"><%= link_to "x", user_friends_path(current_user, :friend_id => @friend), method: :delete, remote: true %></span></li>';
var count = '<%=current_user.friends.count%>';
$('#following ul').append(html);
$('#friend-count').text(count);

app/views/users/instagram_photo.html.erb
<p><img src="<%=@photo%>" alt="most recent instagram photo"></p>

app/views/users/remove_friend.js.erb
$('li #<%=@friend_id%>').remove();
var count = '<%=current_user.friends.count%>';
$('#friend-count').text(count);

app/views/users/show.html.erb
<% if @user == current_user %>
  <%= render partial: "private_profile" %>
<% else %>
  <%= render partial: "public_profile", locals: {user: @user} %>
<% end %>
 