config/routes.rb
Rails.application.routes.draw do
  resources :activities

  devise_scope :user do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_users_session
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :moments

  resources :maps do 
    get '/geojson' => 'maps#geojson'
    post '/send_link_to_friend' => 'maps#send_link_to_friend'
  end

  resources :users do
    post '/follow' => 'users#add_friend_profile'
    get '/friends' => 'users#friends'
    post '/friends' => 'users#add_friend'
    delete '/friends' => 'users#remove_friend'
    get '/geojson' => 'users#geojson'
  end
  
  get '/geojson' => 'welcome#geojson'
  get '/about' => 'welcome#about'

  get '/act/:id' => 'activities#item'
  
  post 'instagram_photo' => 'moments#instagram_photo'

  root 'welcome#index'

end

app/views/layouts/_footer.html.erb
<footer>
    Made with <i class="fa fa-heart" style="color:#d9534f;"></i> by <a href="https://www.github.com/ryannyunn" target="blank">Ryan Yun</a>, <a href="https://www.github.com/walterbm" target="blank">Walter Beller Morales</a>, <a href="https://www.github.com/iandonovanhock" target="blank">Ian Hock</a> &amp; <a href="https://www.github.com/beccaades" target="blank">Becca Ades</a> at <span id="slash" style="color:#15bdde;">//</span> <a href="https://www.flatironschool.com" target="blank" style="text-decoration: none;">Flatiron School</a>. Learn more about this project <%= link_to 'here', about_path %>.
</footer>

app/views/layouts/_logged_in_sidebar.html.erb
<!-- Mainmenu with submenu -->
<li class="has_submenu">
  <a href="#"><i class="fa fa-map"></i> Maps <span class="badge badge-info pull-right"><%= current_user.maps.count %></span><span id="submenu" class="nav-caret fa fa-caret-down"></span></a>
  <!-- Submenu -->
  <ul class="list-unstyled">
    <%= form_tag(("/maps"), :html => {:class => "ui-element-container form-inline"}) do %>
      <div class="input-group input-group-sm">
        <%= text_field_tag 'map[name]', nil, :class => 'form-control', :placeholder => 'Create Map'%>
        <span class="input-group-btn"><%= submit_tag "+", :id => "createmap", :class => "btn btn-info" %></span>
      </div>
    <% end %>
    <% current_user.maps.each do |map| %>
      <li 
      class="mapListItem" ><i class="fa fa-angle-double-right"></i>  
      <%= link_to map.name, map_path(map) %></li>
    <% end %>
  </ul>
</li>
<!-- Mainmenu with submenu -->
<li id= "following" class="has_submenu">
  <a href="#"><i class="fa fa-heart"></i> Following <span class="badge badge-info pull-right" id="friend-count"><%= current_user.friends.count %></span><span id="submenu" class="nav-caret fa fa-caret-down"></span></a>
  <!-- Submenu -->
  <ul class="list-unstyled">
    <%= form_tag(user_friends_path(current_user), remote: true, :html => {:class => "ui-element-container form-inline"}) do %>
      <li><div class="input-group input-group-sm">
        <%= text_field_tag :friend_name, nil, :class => 'form-control', :placeholder => 'Follow' %>
        <span class="input-group-btn"><%= submit_tag "+", :class => "btn btn-info" %></span>
      </div></li>
    <% end %>
    <% current_user.friends.each do |friend| %>
    <li id= '<%=friend.id%>'>
    <%=image_tag friend.avatar.url(:thumb), :class => "img-responsive img-circle-frfo"%>
    <%= link_to friend.name, user_path(friend) %>
    <span class= "pull-right"><%= link_to "x", user_friends_path(current_user, :friend_id => friend.id), method: :delete, remote: true %></span>
    </li>
    <% end %>
  </ul>

</li>
<!-- Mainmenu with submenu -->
<li class="has_submenu">
  <a href="#"><i class="fa fa-users"></i> Followers <span class="badge badge-info pull-right"><%= current_user.followers.count %></span><span id="submenu" class="nav-caret fa fa-caret-down"></span></a>
  <!-- Submenu -->
  <ul class="list-unstyled">
    <% current_user.followers.each do |follower| %>
    <li>
      <%=image_tag follower.avatar.url(:thumb), :class => "img-responsive img-circle-frfo"%>
      <%= link_to follower.name, user_path(follower) %>
    </li>  
    <% end %>
  </ul>
</li>
<li><%= link_to destroy_user_session_path, :method => :delete do %>
  <i class="fa fa-sign-out"></i>
  Sign Out
<% end %></li>
<hr>
<li><a href="<%= root_path %>"><i class="fa fa-commenting"></i>Feed </a></li>
<div class="feed-container">
  <div class="feed-content">
    <ul class="feed-ul">
      <% activity_feed.each do |activity| %>
        <%= render "activities/activity", activity: activity %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_logged_out_sidebar.html.erb
<li><a href="<%= new_user_registration_path %>"><i class="fa fa-user-plus"></i> Sign Up </a></li>
<li><a href="<%= new_user_session_path %>"><i class="fa fa-sign-in"></i> Log In</a></li>

app/views/layouts/_mainbar.html.erb
<!-- Mainbar head starts -->
<div class="main-head">
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div>
</div>
<!-- Mainbar head ends -->

app/views/layouts/_sidebar.html.erb
<!-- Sidebar starts -->
<div class="sidebar">

  <div class="sidey">

    <!-- Logo -->
    <div class="logo" style="padding-top:0">
      <h1><a href="/"><i class="fa fa-map-marker br-lblue"></i></i> Ayer <span>Map Nostalgia</span></a></h1>
    </div>
    
    <!-- Sidebar navigation starts -->
    
    <!-- Responsive dropdown -->
    <div class="sidebar-dropdown"><a href="#" class="br-blue"><i class="fa fa-bars"></i></a></div>
    
    <div class="side-nav" style="padding-top:0">
      <% if user_signed_in? %>
        <%= link_to user_path(current_user) do %>
          <%=image_tag current_user.avatar.url(:thumb), :class => "img-responsive img-circle"%>
        <% end %>
        <%= current_user.name.upcase %>
      <div class="side-nav-block">
        <!-- Sidebar links -->
        <ul class="list-unstyled">
          <%= render partial: "layouts/logged_in_sidebar" %>
        </ul>
      </div>
      <% else %>
        <div class="side-nav-block">
          <!-- Sidebar heading -->
          <h4>Menu</h4>
          <!-- Sidebar links -->
          <ul class="list-unstyled">
            <%= render partial: "layouts/logged_out_sidebar" %>
          </ul>
        </div>
      <% end %>
    </div>
    <!-- Sidebar navigation ends -->
  </div>
</div>
<!-- Sidebar ends -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AYER</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href='https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox.js/v2.2.1/mapbox.js'></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-heat/v0.1.3/leaflet-heat.js'></script>
    <script src="https://cdn.pubnub.com/pubnub-3.7.14.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <div class="outer">
      <%= render partial: "layouts/sidebar" %>
      <div class="mainbar">

      <% if notice %> 
        <div class="alert alert-warning alert-dismissable"><%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
      <% end %>

      <% if alert %> 
        <div class="alert alert-danger alert-dismissable"><%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        </div>
      <% end %>

    <%= yield %>

      </div>
    </div> 
  </body>
</html>